# Generated by Django 4.2 on 2023-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsertedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NUM_PANELA", models.IntegerField(default=0)),
                ("FORNO_FUSAO", models.CharField(max_length=50)),
            ],
        ),
    ]
