# Generated by Django 4.2 on 2023-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Form_Fornos", "0002_inserteddata_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="inserteddata",
            name="COMP_QUIMICA",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="DENSIDADE_ESP",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="FORNO_TORRE",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="HORA",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="LIGA",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="MKR",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="N_P_TORRE",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="REL_MAQUINAS",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="TEMPERATURA",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inserteddata",
            name="TEMP_VAZ_ESPECIFICADO",
            field=models.IntegerField(null=True),
        ),
    ]
