# Generated by Django 4.2 on 2023-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Form_Fornos", "0004_alter_inserteddata_temp_vaz_especificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inserteddata",
            name="TEMP_VAZ_ESPECIFICADO",
            field=models.CharField(max_length=50),
        ),
    ]
